### PR TITLE
Cache coingecko historic price requests for the same date

### PR DESCRIPTION
**Pull request by dmakarov**
sys sync command frequently fails because of seemingly being throttled by coin gecko for fast repeated requests. The same price data is requested multiple times for many accounts. This pr adds a static hashmap to cache the results of previous requests and reuses them in subsequent updates.

### CODE REVIEW

**Comment by mvines** [comment]
Oh nice, this has been bugging me for a while too!

**Comment by dmakarov** [comment]
it should probably include coin in the key. I'll fix it.

**Comment by mvines** [comment]
ty sir

**Comment by dmakarov** [comment]
Not sure whether this is good idiomatic Rust. Please, let me know if it should be done differently.

**Pull request merged**
